### ISSUE TITLE
Service Appointment Standard Fields

### ISSUE THREAD

**Issue by jamienrogers222** [pgonzaleznetwork/HappySoup.io#184]
Hi Pablo,

I'm trying to perform impact analysis on Service Appointment standard fields, specifically Account. However, when I search "Account" (Impact Analysis>Standard Fields) only Account object fields return. When I search "Service Appointment", "ServiceAppointment", "Service_Appointment", or "ServiceAppointment.Account" no results return. Are there only certain Standard Objects the Standard Fields search returns?

**Comment by chummiersmile** [comment]
I'm also having this issue still 2 years later. @pgonzaleznetwork

**Comment by pgonzaleznetwork** [comment]
Not all standard fields are supported. This is a limitation of the Salesforce API. Please use app.salto.io for impact analysis across all fields.
