### ISSUE TITLE
How to find where an org wide email address is used

### ISSUE THREAD

**Issue by JeffKrakowski** [pgonzaleznetwork/HappySoup.io#209]

**Comment by pgonzaleznetwork** [comment]
Hi Jeff,

This needs full text search, something that HappySoup does not support. I work at Salto and we have been filling some of these gaps with our 100% free app for impact analysis, here's a demo of exactly what you are looking for

https://youtu.be/fReJPzBOYdo

**Comment by JeffKrakowski** [comment]
[image: image.png]

-- 

      Jeffrey Krakowski
 *Salesforce Consulting & Administration*
      www.sfchamp.com
      Linkedin.com/in/salesforcechamp
<https://www.linkedin.com/in/SalesforceChamp>

      US: (929) 445-8125
      Israel:054-292-7770
        Join me on Zoom <https://olami.zoom.us/my/smile>
