### ISSUE TITLE
Error scaling dynos: Process tier is invalid. Available process tiers are Eco, Basic, Production, Private, and Shield.

### ISSUE THREAD

**Issue by bmar** [pgonzaleznetwork/HappySoup.io#245]
I think the "Deploy to Heroku" template may be using Heroku's deprecated Free Plan. I get this error when deploying:
Error scaling dynos: Process tier is invalid. Available process tiers are Eco, Basic, Production, Private, and Shield.

**Comment by imansour12** [comment]
did you find a fix?

**Comment by imansour12** [comment]
I found a fix eventually, the deploy to heroku button did not work. Even after I got the Eco package. What I did was I forked the project and created a new heroku application from the dashboard.

**Comment by pgonzaleznetwork** [comment]
Yeah, this was done for the heroku free plan. For now, as recommended above, just fork the project and create a new heroku app.
