### ISSUE TITLE
unable to log into your salesforce org

### ISSUE THREAD

**Issue by cadillacben** [pgonzaleznetwork/HappySoup.io#249]
When trying to login with salesforce I am getting a message saying it failed and to clear my cache.  Here's what I have done so far and I do not know where to go next.

- Used chrome and edge
- incognito in both browsers
- production org
- sandbox org (developer)
- test.salesforce.com
- my domain in sandbox https://pentairwater--bendev.sandbox.my.salesforce.com
- my domain in production

My login history seems ok and I am redirected back to happysoup.io after authenticating with SF.

![image](https://github.com/pgonzaleznetwork/HappySoup.io/assets/17458691/94a21d00-5625-475d-8081-786a7c075fbf)

**Comment by pgonzaleznetwork** [comment]
Hi @cadillacben ,

Thanks for reporting this issue! Do you see a specific error in HappySoup? Also, does your profile have login IP ranges? HappySoup uses Heroku and the IP of Heroku may be out of range.

**Comment by cadillacben** [comment]
I had checked the IP ranges before based on some searching, but I do not have any.  I even added 0.0.0.0-255.255.255.255 just in case but it did not make a difference.

When logging in I get the standard happy soup page, then the salesforce login page, and then I am redirected back to happy soup.  It flashes to https://happysoup.io/?oauthfailed=true very quickly and then lands on https://happysoup.io/?logout=true with the message below.

![image](https://github.com/pgonzaleznetwork/HappySoup.io/assets/17458691/77c8139d-9e25-4af7-af86-44d548a6d6bc)

**Comment by cadillacben** [comment]
@pgonzaleznetwork 
I tried removing MFA as a test and used a different computer, but no luck.  It does seem related to my orgs, but the login seems ok. I could give you a login if it would help.

![image](https://github.com/pgonzaleznetwork/HappySoup.io/assets/17458691/7787bd71-a7db-4d88-b87d-0a2bd5e64350)

**Comment by pgonzaleznetwork** [comment]
@cadillacben sorry for the late reply. I have no idea, it must be something with your org as I'm and other people are able to log in just fine.
