### ISSUE TITLE
missing required code challenge 404 Error - with solution

### ISSUE THREAD

**Issue by danielwublock** [pgonzaleznetwork/HappySoup.io#252]
When following the instructions to run locally, I was getting an error

> webapp-1  | Error: oauth-failed
> webapp-1  |     at /app/backend/routes/oauthRouter.js:17:25
> webapp-1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> webapp-1  |     at next (/app/node_modules/express/lib/router/route.js:137:13)
> webapp-1  |     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
> webapp-1  |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
> webapp-1  |     at /app/node_modules/express/lib/router/index.js:281:22
> webapp-1  |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
> webapp-1  |     at next (/app/node_modules/express/lib/router/index.js:275:10)
> webapp-1  |     at Function.handle (/app/node_modules/express/lib/router/index.js:174:3)
> webapp-1  |     at router (/app/node_modules/express/lib/router/index.js:47:12)
> webapp-1  | GET /oauth2/callback?error=invalid_request&error_description=missing+required+code+challenge 404 5.954 ms - 80
> webapp-1  | node:_http_outgoing:703
> webapp-1  |     throw new ERR_HTTP_HEADERS_SENT('set');

Solution was to go to the Connected App and uncheck "Require Proof Key for Code Exchange (PKCE) Extension for Supported Authorization Flows" which was checked automatically. This appears to be a relatively new default setting which causes issues for people https://trailhead.salesforce.com/trailblazer-community/feed/0D54V00007T42fmSAB

Just creating this issue so that maybe the README instructions for creating the Connected App can be updated to include this new step. Thanks

**Comment by pgonzaleznetwork** [comment]
Thanks a lot!
